<?php
/**
 * Inline SVG icons.
 *
 * Icons live in assets/images/icon/ as files committed to the repo, generated by
 * `npm run make:icon <set>:<name>`. They are inlined rather than served through
 * an <img> so they inherit currentColor and cost no extra request.
 *
 * Read through template-parts/icon.php rather than called directly from a
 * template, so markup stays in the template layer.
 */

/**
 * Return one icon's markup, or an empty string when it cannot be resolved.
 *
 * Never echoes and never warns: a missing icon degrades to nothing rather than
 * taking the page down with it.
 */
function drg_get_icon( $name, $class = '' ) {
    // one read per icon per request, however many times a template asks for it
    static $cache = array();

    if ( ! is_string( $name ) || ! preg_match( '/^[a-z0-9-]+$/', $name ) ) {
        return '';
    }

    if ( ! isset( $cache[ $name ] ) ) {
        $path = get_theme_file_path( 'assets/images/icon/' . $name . '.svg' );

        $cache[ $name ] = file_exists( $path ) ? trim( (string) file_get_contents( $path ) ) : '';
    }

    if ( '' === $cache[ $name ] ) {
        return '';
    }

    // decorative by default -- an icon next to its own label has nothing to add
    // for a screen reader, and focusable="false" keeps IE/Edge out of the tab order
    $attributes = ' aria-hidden="true" focusable="false"';

    if ( is_string( $class ) && '' !== $class ) {
        $attributes .= ' class="' . esc_attr( $class ) . '"';
    }

    return preg_replace( '/<svg\b/', '<svg' . $attributes, $cache[ $name ], 1 );
}
